document.addEventListener("DOMContentLoaded", () => {
    document.title = `${CONFIG.country} ${CONFIG.year}`;
    document.getElementById('header-title').textContent = `${CONFIG.country} ${CONFIG.year}`;
    document.getElementById('header-subtitle').textContent = CONFIG.dates;

    const mainWrapper = document.getElementById('main-wrapper');
    const thumbWrapper = document.getElementById('thumb-wrapper');
    const pageIndicator = document.getElementById('page-indicator');

    const getPageLabel = (index) => {
        if (index === 0) return "Cover";
        return `Page ${index * 2 - 1}-${index * 2}`;
    };

    const handleImageError = (img) => {
        img.closest('.swiper-slide').classList.add('image-missing');
    };

    // Responsive WebP variants generated by scripts/optimize_images.py;
    // the original JPEGs remain as the <img> fallback.
    const MAIN_WIDTHS = [800, 1600, 2400];
    const MAIN_SIZES = '100vw';

    // Native loading="lazy" doesn't work inside Swiper (every slide gets fetched
    // up front), so pages keep their URLs in data-* attributes until needed.
    const loadSlide = (index) => {
        const slide = mainWrapper.children[index];
        const img = slide?.querySelector('.main-image');
        if (!img || !img.dataset.src) return;
        const source = slide.querySelector('source');
        source.srcset = source.dataset.srcset;
        img.src = img.dataset.src;
        delete img.dataset.src;
    };

    // Load the current page plus its neighbours so swiping feels instant.
    const loadAround = (index) => {
        [index, index + 1, index - 1, index + 2].forEach(loadSlide);
    };

    // When zoomed in, ask the browser for a larger variant so the page stays sharp.
    const updateZoomSizes = (imageEl, scale) => {
        const source = imageEl?.closest('picture')?.querySelector('source');
        if (source) source.sizes = scale > 1 ? `${Math.ceil(scale * 100)}vw` : MAIN_SIZES;
    };

    // --- Build slides ---
    for (let i = 0; i < CONFIG.totalImages; i++) {
        const label = getPageLabel(i);
        const baseName = `${CONFIG.imagePrefix}${i}`;
        const fileName = `${baseName}.jpg`;
        const isFirst = i === 0;

        // Main Slide
        const mainSlide = document.createElement('div');
        mainSlide.className = 'swiper-slide';
        mainSlide.innerHTML = `
            <div class="swiper-zoom-container">
                <picture>
                    <source type="image/webp" sizes="${MAIN_SIZES}"
                        data-srcset="${MAIN_WIDTHS.map(w => `webp/${baseName}-${w}.webp ${w}w`).join(', ')}">
                    <img data-src="${fileName}" alt="${label}" class="main-image" decoding="async"${isFirst ? ' fetchpriority="high"' : ''}>
                </picture>
            </div>`;
        mainSlide.querySelector('.main-image').addEventListener('error', (e) => handleImageError(e.target));
        mainWrapper.appendChild(mainSlide);

        // Thumb Slide
        const thumbSlide = document.createElement('div');
        thumbSlide.className = 'swiper-slide';
        thumbSlide.innerHTML = `
            <picture>
                <source type="image/webp" srcset="${CONFIG.thumbnailFolder}${baseName}.webp">
                <img src="${CONFIG.thumbnailFolder}${fileName}" alt="${label}" class="thumb-image"
                    loading="lazy" decoding="async">
            </picture>
            <div class="thumb-label">${label}</div>
        `;
        thumbSlide.querySelector('.thumb-image').addEventListener('error', (e) => handleImageError(e.target));
        thumbWrapper.appendChild(thumbSlide);
    }

    pageIndicator.textContent = getPageLabel(0);

    // --- Initialize Swipers ---
    const thumbSwiper = new Swiper('.thumb-swiper', {
        spaceBetween: 10,
        slidesPerView: 6,
        freeMode: true,
        watchSlidesProgress: true,
        breakpoints: {
            320: { slidesPerView: 3 },
            640: { slidesPerView: 4 },
            1024: { slidesPerView: 6 }
        }
    });

    const mainSwiper = new Swiper('.main-viewer', {
        spaceBetween: 0,
        speed: 400,
        grabCursor: true,
        zoom: true,
        keyboard: {
            enabled: true,
        },
        thumbs: {
            swiper: thumbSwiper,
        },
        on: {
            init: function () {
                loadAround(this.activeIndex);
            },
            slideChange: function () {
                pageIndicator.textContent = getPageLabel(this.activeIndex);
                loadAround(this.activeIndex);
            },
            zoomChange: function (swiper, scale, imageEl) {
                updateZoomSizes(imageEl, scale);
            }
        }
    });

    // --- Navigation ---
    document.querySelector('.prev-zone').addEventListener('click', (e) => {
        e.stopPropagation();
        mainSwiper.slidePrev();
    });
    document.querySelector('.next-zone').addEventListener('click', (e) => {
        e.stopPropagation();
        mainSwiper.slideNext();
    });

    // --- Fullscreen Toggle ---
    document.getElementById('main-viewer').addEventListener('click', () => {
        document.body.classList.toggle('is-fullscreen');
        // Force Swiper to recalculate dimensions after layout change
        setTimeout(() => {
            mainSwiper.update();
        }, 100);
    });
});
